services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack-server
#    volumes:
#      - ./.docker/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
      - "8001:8001"
    restart: always
